import type { Alumni, Article } from "@/lib/mock-data";

export const curatedAlumni: Alumni[] = [
  {
    id: "maxerslover-2024-whu",
    name: "maxerslover",
    graduationYear: 2024,
    className: "13班",
    university: "武汉大学",
    college: "弘毅学堂",
    major: "微电子科学与技术",
    city: "武汉",
    country: "中国",
    stage: "本科在读",
    direction: "先进封装技术",
    tags: ["微电子", "高中学习", "志愿填报", "大学专业", "科研竞赛"],
    intro: "我是一个略显慵懒的猫。",
    gaokaoYear: 2024,
    gaokaoProvince: "湖南",
    gaokaoType: "物化生",
    gaokaoScore: 665,
    gaokaoRank: 0,
    showScore: true,
    showRank: false,
    admittedUniversity: "武汉大学",
    admittedMajor: "弘毅学堂（理科试验班）",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "公开高考信息：665+，物理类全省前 0.25%。",
    contact: "全平台：maxerslover",
    showContact: true,
  },
  {
    id: "jalex-2024-xjtlu",
    name: "Jalex",
    graduationYear: 2024,
    className: "13A",
    university: "西交利物浦大学",
    college: "数学物理学院",
    major: "应用数学",
    city: "苏州",
    country: "中国",
    stage: "本科在读",
    direction: "计划继续硕博",
    tags: ["数学人", "英港新德留学", "中外合办本"],
    intro: "西浦应数本科在读～",
    gaokaoYear: 2024,
    gaokaoProvince: "江苏",
    gaokaoType: "物化生",
    gaokaoScore: 612,
    gaokaoRank: 9990,
    showScore: true,
    showRank: true,
    admittedUniversity: "西交利物浦大学",
    admittedMajor: "电子信息类",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "乡野小城藏不住少年锋芒，世间风月皆待你我踏迹前往。",
    contact: "微信：jalexjtlu",
    showContact: true,
  },
  {
    id: "xin-yuan-2024-bupt",
    name: "心远",
    graduationYear: 2024,
    className: "13A",
    university: "北京邮电大学",
    college: "网络空间安全学院",
    major: "信息安全",
    city: "北京",
    country: "中国",
    stage: "本科在读",
    direction: "生成式隐写、智能体开发/算法优化",
    tags: ["计算机", "志愿填报", "大学本科科研人"],
    intro: "如果你想从事计算机行业，又想要在时代浪潮席卷前找到你一席之地，可以联系我",
    gaokaoYear: 2024,
    gaokaoProvince: "北京",
    gaokaoType: "物化生",
    gaokaoScore: 626,
    gaokaoRank: 6000,
    showScore: true,
    showRank: true,
    admittedUniversity: "北京邮电大学",
    admittedMajor: "大数据管理与应用",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "作为一个唯心主义者，我觉得热情远比能力重要得多",
    contact: "微信：17375901820",
    showContact: true,
  },
  {
    id: "zhi-he-yi-dian-dian-2024-hunnu",
    name: "只喝一點點",
    graduationYear: 2024,
    className: "13班",
    university: "湖南师范大学",
    college: "数学与统计学院",
    major: "数学与应用数学",
    city: "长沙",
    country: "中国",
    stage: "本科在读",
    direction: "教师",
    tags: ["师范", "数学辅导", "教育类"],
    intro: "一句话无法介绍我自己",
    gaokaoYear: 2024,
    gaokaoProvince: "湖南",
    gaokaoType: "物化生",
    gaokaoScore: 593,
    gaokaoRank: 17000,
    showScore: false,
    showRank: true,
    admittedUniversity: "湖南师范大学",
    admittedMajor: "数学与应用数学",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "该学的时候学，该玩的时候玩，主次分清。",
    contact: "",
    showContact: false,
  },
];

export const curatedArticles: Article[] = [
  {
    id: "maxerslover-my-experience",
    title: "我的经历",
    excerpt: "我会伸出还温热的手掌，告诉他明天会有多晴朗。",
    category: "高中学习",
    authorName: "maxerslover",
    authorId: "maxerslover-2024-whu",
    graduationYear: 2024,
    readTime: "1 分钟",
    submittedAt: "2026/6/12 18:33",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "……",
      "最想告诉学弟学妹：我会伸出还温热的手掌，告诉他明天会有多晴朗",
      "如果重新回到高三：我想知道高考答案🙈",
    ],
  },
  {
    id: "jalex-system-test",
    title: "选择＞努力",
    excerpt: "高考前后仿佛是两段截然不同的人生。所谓自由，不是拥有所有选择，而是有勇气选择真正适合自己的路。",
    category: "留学申请",
    authorName: "Jalex",
    authorId: "jalex-2024-xjtlu",
    graduationYear: 2024,
    readTime: "2 分钟",
    submittedAt: "2026/6/12 11:47",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "回想起两年前的 2024 届高考：\n敬那个熬过高中三年的自己🙏",
      "我从未怀念过高中的日子。那是一段汗水💦与眼泪交织的岁月，有压力、有迷茫，也有很多个怀疑自己的瞬间。\n但我始终感激一路陪我走来的家人，感激在我最低谷时拉了我一把的刘老师👨🏻‍🏫，也感激那些陪我一起度过青春的同学们。正是因为有你们，那段艰难的时光才有了温度。",
      "对我来说，选择西交利物浦大学，高考前后仿佛是两段截然不同的人生，甚至有一种“穿越”般的感觉。如果再给我一次机会，我依然会“浪费”那四十多分，把第一志愿填给西浦。\n因为这里给了我真正想要的东西：一扇通往更广阔世界的大门🌍",
      "人生并不总是选择别人眼中“最优”的答案。有时候，看似“大材小用”的决定，反而最贴近自己真正想要的人生。\n这两年，我依然会对未来反复思考、不断纠结。就像高考前半年，我无数次想象西浦会是什么样子。如今，我又对更远的世界充满好奇。",
      "我逐渐明白，所谓自由，不是拥有所有选择，而是有勇气选择真正适合自己的路✨想清楚为什么出发，行动才会有意义；而有了意义，才会有坚持下去的力量。",
      "敬过去那个勇敢选择的自己，也敬未来依然敢于选择的自己🍻",
      "最想告诉学弟学妹：乡野小城藏不住少年锋芒，世间风月皆待你我踏迹前往。",
      "如果重新回到高三：我从不对自己做的选择后悔",
      "联系方式：微信 jalexjtlu",
    ],
  },
  {
    id: "xin-yuan-computer-career",
    title: "如何入门计算机行业？",
    excerpt: "人应该自负一点，尽管你什么也没有。作为一个唯心主义者，我觉得热情远比能力重要得多。",
    category: "职业发展",
    authorName: "心远",
    authorId: "xin-yuan-2024-bupt",
    graduationYear: 2024,
    readTime: "1 分钟",
    submittedAt: "2026/6/12 13:55",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "人应该自负一点，尽管你什么也没有。",
      "最想告诉学弟学妹：作为一个唯心主义者，我觉得热情远比能力重要得多。",
      "如果重新回到高三：哈哈哈哈我觉得到现在已经很圆满了，我不需要改变什么。",
      "联系方式：微信 17375901820",
    ],
  },
  {
    id: "zhi-he-yi-dian-dian-back-to-xupu",
    title: "从溆浦一中到溆浦一中",
    excerpt: "建议大学多体验。该学的时候学，该玩的时候玩，主次分清。",
    category: "高中学习",
    authorName: "只喝一點點",
    authorId: "zhi-he-yi-dian-dian-2024-hunnu",
    graduationYear: 2024,
    readTime: "1 分钟",
    submittedAt: "2026/6/12 15:50",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "建议大学多体验。",
      "最想告诉学弟学妹：该学的时候学，该玩的时候玩，主次分清。",
      "如果重新回到高三：高考完不会选师范。",
    ],
  },
];
