import type { Alumni, Article } from "@/lib/mock-data";

export const curatedAlumni: Alumni[] = [
  {
    id: "jalex-2024-xjtlu",
    name: "Jalex",
    graduationYear: 2024,
    className: "13B",
    university: "西交利物浦大学",
    college: "数学物理学院",
    major: "应用数学",
    city: "苏州",
    country: "中国",
    stage: "本科在读",
    direction: "计划继续硕博",
    tags: ["数学人", "英港新德留学", "中外合办本"],
    intro: "西浦应数本科在读～",
    gaokaoYear: 2024,
    gaokaoProvince: "江苏",
    gaokaoType: "物化生",
    gaokaoScore: 612,
    gaokaoRank: 9990,
    showScore: true,
    showRank: true,
    admittedUniversity: "西交利物浦大学",
    admittedMajor: "电子信息类",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "乡野小城藏不住少年锋芒，世间风月皆待你我踏迹前往。",
    contact: "微信：jalexjtlu",
    showContact: true,
  },
  {
    id: "xin-yuan-2024-bupt",
    name: "心远",
    graduationYear: 2024,
    className: "13A",
    university: "北京邮电大学",
    college: "网络空间安全学院",
    major: "信息安全",
    city: "北京",
    country: "中国",
    stage: "本科在读",
    direction: "生成式隐写、智能体开发/算法优化",
    tags: ["计算机", "志愿填报", "大学本科科研人"],
    intro: "如果你想从事计算机行业，又想要在时代浪潮席卷前找到你一席之地，可以联系我",
    gaokaoYear: 2024,
    gaokaoProvince: "北京",
    gaokaoType: "物化生",
    gaokaoScore: 626,
    gaokaoRank: 6000,
    showScore: true,
    showRank: true,
    admittedUniversity: "北京邮电大学",
    admittedMajor: "大数据管理与应用",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "作为一个唯心主义者，我觉得热情远比能力重要得多",
    contact: "微信：17375901820",
    showContact: true,
  },
  {
    id: "zhi-he-yi-dian-dian-2024-hunnu",
    name: "只喝一點點",
    graduationYear: 2024,
    className: "13班",
    university: "湖南师范大学",
    college: "数学与统计学院",
    major: "数学与应用数学",
    city: "长沙",
    country: "中国",
    stage: "本科在读",
    direction: "教师",
    tags: ["师范", "数学辅导", "教育类"],
    intro: "一句话无法介绍我自己",
    gaokaoYear: 2024,
    gaokaoProvince: "湖南",
    gaokaoType: "物化生",
    gaokaoScore: 593,
    gaokaoRank: 17000,
    showScore: false,
    showRank: true,
    admittedUniversity: "湖南师范大学",
    admittedMajor: "数学与应用数学",
    studyAdvice: "",
    examAdvice: "",
    applicationAdvice: "",
    majorAdvice: "",
    messageToStudents: "该学的时候学，该玩的时候玩，主次分清。",
    contact: "",
    showContact: false,
  },
];

export const curatedArticles: Article[] = [
  {
    id: "jalex-system-test",
    title: "选择＞努力",
    excerpt: "系统测试哈～ 乡野小城藏不住少年锋芒，世间风月皆待你我踏迹前往。",
    category: "职业发展",
    authorName: "Jalex",
    graduationYear: 2024,
    readTime: "1 分钟",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "系统测试哈～",
      "最想告诉学弟学妹：乡野小城藏不住少年锋芒，世间风月皆待你我踏迹前往。",
      "如果重新回到高三：我从不对自己做的选择后悔",
      "联系方式：微信 jalexjtlu",
    ],
  },
  {
    id: "xin-yuan-computer-career",
    title: "如何入门计算机行业？",
    excerpt: "人应该自负一点，尽管你什么也没有。作为一个唯心主义者，我觉得热情远比能力重要得多。",
    category: "职业发展",
    authorName: "心远",
    graduationYear: 2024,
    readTime: "1 分钟",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "人应该自负一点，尽管你什么也没有。",
      "最想告诉学弟学妹：作为一个唯心主义者，我觉得热情远比能力重要得多。",
      "如果重新回到高三：哈哈哈哈我觉得到现在已经很圆满了，我不需要改变什么。",
      "联系方式：微信 17375901820",
    ],
  },
  {
    id: "zhi-he-yi-dian-dian-back-to-xupu",
    title: "从溆浦一中到溆浦一中",
    excerpt: "建议大学多体验。该学的时候学，该玩的时候玩，主次分清。",
    category: "高中学习",
    authorName: "只喝一點點",
    graduationYear: 2024,
    readTime: "1 分钟",
    likeCount: 0,
    favoriteCount: 0,
    paragraphs: [
      "建议大学多体验。",
      "最想告诉学弟学妹：该学的时候学，该玩的时候玩，主次分清。",
      "如果重新回到高三：高考完不会选师范。",
    ],
  },
];
